# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-qtcalc"
BBFILE_PATTERN_meta-qtcalc = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-qtcalc = "6"

LAYERDEPENDS_meta-qtcalc = "core qt6-layer"
LAYERSERIES_COMPAT_meta-qtcalc = "scarthgap"
