# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/youhana/YOCTO/poky/meta \
  /home/youhana/YOCTO/poky/meta-poky \
  /home/youhana/YOCTO/poky/meta-yocto-bsp \
  /home/youhana/YOCTO/meta-raspberrypi \
  /home/youhana/YOCTO/meta-test \
  /home/youhana/YOCTO/meta-openembedded/meta-oe \
  /home/youhana/YOCTO/meta-openembedded/meta-python \
  /home/youhana/YOCTO/meta-qt6 \
  /home/youhana/YOCTO/meta-qtcalc \
  /home/youhana/YOCTO/meta-ros/meta-ros-common \
  /home/youhana/YOCTO/meta-ros/meta-ros2 \
  /home/youhana/YOCTO/meta-ros/meta-ros2-humble \
  "
